### ISSUE TITLE
Jcliff role dont allow to install jcliff on macos catalina

### ISSUE THREAD

**Issue by cmoulliard** [wildfly-extras/ansible_collections_jcliff#12]
## Issue

Jcliff role dont allow to install jcliff on macos catalina

### Playbook
```
- hosts: localhost
  gather_facts: false
  collections:
    - redhat.jcliff

  tasks:
    - name: Include Jcliff role
      include_role:
        name: jcliff
    - jcliff:
        wfly_home: /Users/cmoulli/servers/wildfly-20.0.0.Final
        subsystems:
          - system_props:
              - name: jcliff.enabled
                value: 'enabled'
              - name: jcliff.version
                value: '1.0'
```

### Result

```
TASK [redhat.jcliff.jcliff : Collect Supported Operating Systems] ******************************************************************************************************************************************************************
ok: [localhost] => (item={'key': 'rpm', 'value': ['Fedora', 'CentOS', 'RedHat']})
ok: [localhost] => (item={'key': 'homebrew', 'value': ['MacOSX']})

TASK [redhat.jcliff.jcliff : Verify supported Operating Systems] *******************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"assertion": "ansible_distribution is not undefined", 
"changed": false,
"evaluated_to": false,
"msg": "Unsppoorted Operating system for package installation"}
```
