### ISSUE TITLE
Jcliff module do not work on macos - "error": "bash: /usr/bin/jcliff: No such file or directory"

### ISSUE THREAD

**Issue by cmoulliard** [wildfly-extras/ansible_collections_jcliff#14]
## Issue

`Jcliff module` do not work on macos as it is installed under a different path using the homebrew tool

### Playbook tested

```
- hosts: localhost
  # gather_facts: false
  collections:
    - redhat.jcliff

  tasks:
    - jcliff:
        wfly_home: $HOME/servers/wildfly-20.0.0.Final
        jcliff_home: /usr/local/Cellar/jcliff/2.12.5
        rules_dir: $HOME/temp/jcliff_rules
        subsystems:
          - system_props:
              - name: jcliff.enabled
                value: 'enabled'
              - name: jcliff.version
                value: '1.0'
```
### Result

```
<localhost> EXEC /bin/sh -c 'rm -f -r /Users/cmoullia/.ansible/tmp/ansible-tmp-1593163804.734702-32844-147248928971729/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "debug_mode": false,
            "jcliff": "/usr/bin/jcliff",
            "jcliff_home": "/usr/local/Cellar/jcliff/2.12.5",
            "jcliff_jvm": "/Users/cmoullia/.sdkman/candidates/java/current",
            "management_host": "localhost",
            "management_password": null,
            "management_port": "9990",
            "management_username": null,
            "remote_rulesdir": "/Users/cmoullia/.ansible/tmp/ansible-tmp-1593163804.734702-32844-147248928971729/",
            "rule_file": null,
            "rules_dir": "/Users/cmoullia/temp/jcliff_rules",
            "state": "present",
            "subsystems": [
                {
                    "datasources": null,
                    "deployments": null,
                    "drivers": null,
                    "keycloak": null,
                    "system_props": [
                        {
                            "name": "jcliff.enabled",
                            "value": "enabled"
                        },
                        {
                            "name": "jcliff.version",
                            "value": "1.0"
                        }
                    ]
                }
            ],
            "wfly_home": "/Users/cmoullia/servers/wildfly-20.0.0.Final"
        }
    },
    "meta": {
        "failed": true,
        "report": {
            "JAVA_HOME": "/Users/cmoullia/.sdkman/candidates/java/current",
            "JBOSS_HOME": "/Users/cmoullia/servers/wildfly-20.0.0.Final",
            "JCLIFF_HOME": "/usr/local/Cellar/jcliff/2.12.5",
            "error": "bash: /usr/bin/jcliff: No such file or directory\n",
            "jcliff_cli": [
                "bash",
                "-x",
                "/usr/bin/jcliff",
                "--cli=/Users/cmoullia/servers/wildfly-20.0.0.Final/bin/jboss-cli.sh",
                "--ruledir=/Users/cmoullia/temp/jcliff_rules",
                "--controller=localhost:9990",
                "-v",
                "/Users/cmoullia/.ansible/tmp/ansible-tmp-1593163804.734702-32844-147248928971729//system_props.jcliff.yml"
            ],
            "output": null,
            "status": 127
        }
    }
}
```
